pmemcheck: merge instruction pointers from inlined functions
pmem/valgrind pull request #76
Opened 2020-01-22 21:42 UTC by marcinslusarz

This speeds up some very specific workloads (where compiler decides to inline memcpy) by a very large factor (>30mins to 0.5s), but has a negligible impact on normal code.

2020-01-24 09:57 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/76)* status: all files reviewed, 5 unresolved discussions (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 431 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLwPYZ6fsNSy5Cw96R:-LzLwPY_0S-k-b9MWOrc:b-fuhp06) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L431)):*
> ```C
> 	 * Copy file name, because original pointer will be overwritten
>          * the next time get_filename will be called.
>          */
> ```

Indentation.
___
*[pmemcheck/pmc_main.c, line 436 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLwSN-0puUQFIuEts5:-LzLwSN-0puUQFIuEts6:b-udbp85) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L436)):*
> ```C
> 	/*
> 	 * Try to keep it on the stack.
> 	 */
> ```

single-line?
___
*[pmemcheck/pmc_main.c, line 454 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLx6du8jDXpkmEn662:-LzLx6du8jDXpkmEn663:b-tvhrdx) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L454)):*
> ```C
> 	 * not mergeable.
> 	 */
> 	Bool files_eq = VG_(strcmp)(filename1, filename) == 0;
> ```

The variable names are a little bit confusing.

a1 -> filename -> filename1
a2 -> filename

I think one additional pointer won't overall destroy performance so maybe do something as follows:

a1 -> filename_transient -> filename1
a2 -> filename2

Just thinking out loud.
___
*[pmemcheck/pmc_main.c, line 491 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLynX1C342sMaeD4ds:-LzLynX1C342sMaeD4dt:b-kwsyfk) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L491)):*
> ```C
> 	/*
> 	 * If both IPs belong to function with memcpy in the name, then
> 	 * consider them the same.
> ```

**as** the same.
___
*[pmemcheck/pmc_main.c, line 496 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLyytLCewMuJR1BamW:-LzLyytLCewMuJR1BamX:b-7h8mng) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L496)):*
> ```C
> 		return True;
> 
> 	/* Same story for memset. */
> ```

with?


<!-- Sent from Reviewable.io -->

2020-03-13 17:27 UTC, marcinslusarz reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/76)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[pmemcheck/pmc_main.c, line 431 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLwPYZ6fsNSy5Cw96R:-M2JusJfCg2hUdbAgeAD:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L431)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[pmemcheck/pmc_main.c, line 436 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLwSN-0puUQFIuEts5:-M2JuuWZAwZtHAa4nRzU:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L436)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

single-line?
</blockquote></details>

Done.
___
*[pmemcheck/pmc_main.c, line 454 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLx6du8jDXpkmEn662:-M2JvW2F6kkaR61oZZj8:bmjdjpx) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L454)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The variable names are a little bit confusing.

a1 -> filename -> filename1
a2 -> filename

I think one additional pointer won't overall destroy performance so maybe do something as follows:

a1 -> filename_transient -> filename1
a2 -> filename2

Just thinking out loud.
</blockquote></details>

Is it better now?
___
*[pmemcheck/pmc_main.c, line 491 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLynX1C342sMaeD4ds:-M2JveJD7Dfsq92kw62d:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L491)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**as** the same.
</blockquote></details>

Done.
___
*[pmemcheck/pmc_main.c, line 496 at r1](https://reviewable.io/reviews/pmem/valgrind/76#-LzLyytLCewMuJR1BamW:-M2JviC1A5MrU6lEAekn:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/37998f6aa5c1920b07aeb291f90aef26ab99d493/pmemcheck/pmc_main.c#L496)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

with?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-13 18:45 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/76)* status: all files reviewed, 1 unresolved discussion (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 466 at r2](https://reviewable.io/reviews/pmem/valgrind/76#-M2KCKjHCFxzVZsd1DOA:-M2KCKjIA1hxebSjW9hy:b1m2ifv) ([raw file](https://github.com/pmem/valgrind/blob/667eb2dc0de50b894045a2dd82c55a778a25b630/pmemcheck/pmc_main.c#L466)):*
> ```C
> 	const HChar *filename;
> 
> 	if (!VG_(get_filename)(ep, a1, &filename))
> ```

If we call ```address_belong_to_memcpy_memset()``` no matter if this call will fail or not what is the point of performing this function to the end?


<!-- Sent from Reviewable.io -->

2020-03-16 14:24 UTC, marcinslusarz reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/76)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[pmemcheck/pmc_main.c, line 466 at r2](https://reviewable.io/reviews/pmem/valgrind/76#-M2KCKjHCFxzVZsd1DOA:-M2Yhgcq9hlhdi7zqA1M:bx15ami) ([raw file](https://github.com/pmem/valgrind/blob/667eb2dc0de50b894045a2dd82c55a778a25b630/pmemcheck/pmc_main.c#L466)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If we call ```address_belong_to_memcpy_memset()``` no matter if this call will fail or not what is the point of performing this function to the end?
</blockquote></details>

address_belong_to_memcpy_memset will be called only if line numbers are different

this patch is supposed to help when the whole function gets inlined into one line, but errors are triggered at different IPs of the original function


<!-- Sent from Reviewable.io -->

2020-03-16 19:10 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/76#-:-M2ZkKkHAMIJugm2VUki:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-04-01 09:37 UTC, merged