pmemcheck: optimize "is pmem" check
pmem/valgrind pull request #78
Opened 2020-01-23 15:31 UTC by marcinslusarz

This check is performed for each store the application makes, so it's
important it is quick. Cache the last pmem & nonpmem region and inline
the region overlapping function to speed it up.

This reduces time of some pmemobj tests by ~20%, but on average
the reductions is only around 5-10%.

2020-01-24 12:06 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78)* status: all files reviewed, 5 unresolved discussions (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 163 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPGzHC9GWClxNqgvP:-LzMPGzHC9GWClxNqgvQ:bkgsyad) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L163)):*
> ```C
> static struct pmem_st *LastPMEM = NULL;
> 
> /** Cached last non-pmem region. */
> ```

the last?
___
*[pmemcheck/pmc_main.c, line 164 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPJB-A9YxTv6jXZ5Y:-LzMPJB-A9YxTv6jXZ5Z:b-7ydddn) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L164)):*
> ```C
> 
> /** Cached last non-pmem region. */
> static struct pmem_st *LastNONPMEM = NULL;
> ```

I'm not sure these globals should start with big letters.
___
*[pmemcheck/pmc_main.c, line 192 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPyQD0XV3t6s8-IHD:-LzMPyQD0XV3t6s8-IHE:b3fqin4) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L192)):*
> ```C
>     } else {
>         struct pmem_st *pmem_st = VG_(OSetGen_Lookup)(pmem.pmem_mappings, &tmp);
>         if (pmem_st)
> ```

Is it possible both nonpmem_st and pmem_st are NULL?
___
*[pmemcheck/pmc_main.c, line 1682 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMQMZACwpY1neNbs4Y:-LzMQMZB0e2Omo74JvQu:bmywmak) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L1682)):*
> ```C
> 
>             LastPMEM = NULL;
>             LastNONPMEM = NULL;
> ```

Can we optimize zeroing this caches? It potentially eats up parts of the benefits.
___
*[pmemcheck/pmc_main.c, line 1903 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMQoEEB78Z8OcZi3JZ:-LzMQoEFByTUVEXHwWDk:bboiy8s) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L1903)):*
> ```C
> 
>     pmem.nonpmem_mappings = VG_(OSetGen_Create)(/*keyOff*/0, cmp_pmem_st,
>             VG_(malloc), "pmc.main.cpci.5", VG_(free));
> ```

"5" relates to the position of the field in the pmem structure?


<!-- Sent from Reviewable.io -->

2020-02-26 16:17 UTC, lplewa reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78)* status: all files reviewed, 6 unresolved discussions (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 174 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-M11HDDZ9yOILvMnv2S5:-M11HDD_C1upGyHut6JB:b-94xams) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L174)):*
> ```C
> */
> static inline __attribute__((always_inline)) Bool
> is_pmem_access(Addr addr, SizeT size)
> ```

what is more probable address which is pmem or non-pmem one?

if pmem is more probable please change order of checks 


<!-- Sent from Reviewable.io -->

2020-03-13 17:54 UTC, marcinslusarz reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi and @lplewa)

___
*[pmemcheck/pmc_main.c, line 163 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPGzHC9GWClxNqgvP:-M2Jz2vG-9g6JQCZSQsu:bayyt8j) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L163)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the last?
</blockquote></details>

I think it's correct.
___
*[pmemcheck/pmc_main.c, line 164 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPJB-A9YxTv6jXZ5Y:-M2Jz7VO6t_bMYQi14t0:bu3rs68) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure these globals should start with big letters.
</blockquote></details>

I don't really care. Done.
___
*[pmemcheck/pmc_main.c, line 174 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-M11HDDZ9yOILvMnv2S5:-M2JzD8NDHk_FCz40_Mm:b-pi0cbc) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L174)):*
<details><summary><i>Previously, lplewa (Łukasz Plewa) wrote…</i></summary><blockquote>

what is more probable address which is pmem or non-pmem one?

if pmem is more probable please change order of checks 
</blockquote></details>

It depends on the traced application. 
___
*[pmemcheck/pmc_main.c, line 192 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPyQD0XV3t6s8-IHD:-M2K-_xT4A9bELGSknLe:b32wsm) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it possible both nonpmem_st and pmem_st are NULL?
</blockquote></details>

no
___
*[pmemcheck/pmc_main.c, line 1682 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMQMZACwpY1neNbs4Y:-M2K-qsC4aX5tv4zEIb8:b-ui1nfs) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L1682)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we optimize zeroing this caches? It potentially eats up parts of the benefits.
</blockquote></details>

add_region/remove_region can reallocate nodes we are caching in these variables
___
*[pmemcheck/pmc_main.c, line 1903 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMQoEEB78Z8OcZi3JZ:-M2K0ZpM-cIMcPjCJJAd:b-v3yol0) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L1903)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

"5" relates to the position of the field in the pmem structure?
</blockquote></details>

It's the 5th type of allocation in this function.
It's just an identifier to make it easier to find the origin of all allocations, in case of memory leaks in pmemcheck itself.


<!-- Sent from Reviewable.io -->

2020-03-13 18:57 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78)* status: all files reviewed, 2 unresolved discussions (waiting on @lplewa and @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 192 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPyQD0XV3t6s8-IHD:-M2KF7Sh2BElc676u0j-:b-ta1pct) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L192)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

no
</blockquote></details>

So what this ```if``` is checking if at this point we know ```nonpmem_st``` is NULL ergo ```pmem_st``` can not.


<!-- Sent from Reviewable.io -->

2020-03-16 15:57 UTC, marcinslusarz reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @lplewa)

___
*[pmemcheck/pmc_main.c, line 192 at r1](https://reviewable.io/reviews/pmem/valgrind/78#-LzMPyQD0XV3t6s8-IHD:-M2Z2_h18A2PbDJQNXoc:b-uymzal) ([raw file](https://github.com/pmem/valgrind/blob/4d95c455952ee1e627886a7413ebfaa53fa14264/pmemcheck/pmc_main.c#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So what this ```if``` is checking if at this point we know ```nonpmem_st``` is NULL ergo ```pmem_st``` can not.
</blockquote></details>

right, I added an assert


<!-- Sent from Reviewable.io -->

2020-03-16 19:12 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/78#-:-M2ZkZb01hrKirNetybR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lplewa)



<!-- Sent from Reviewable.io -->

2020-04-01 09:37 UTC, merged